# Generated by Django 4.0.8 on 2026-01-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
