# Generated by Django 4.0.8 on 2026-01-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_created_at_alter_client_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.CharField(max_length=150, verbose_name='Срок подписка и коменратия'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
