# Generated by Django 4.0.8 on 2026-01-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='client',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. информация'),
        ),
        migrations.AddField(
            model_name='client',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пакет / комментарий'),
        ),
    ]
