# Generated by Django 4.0.8 on 2026-01-06 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0011_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название пакета')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/мес.')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акционный')),
                ('promo_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.TextField(verbose_name='Выбранные пакеты')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
        ),
    ]
