# Generated by Django 4.0.8 on 2026-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_package_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон +'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Цена/мес.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Баланс менеджера'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Телефон +992'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_cost',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
