# Generated by Django 6.0.1 on 2026-01-14 15:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_transaction_client_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Формат: 0000 0000 0000 0000', max_length=19, verbose_name='Номер карты')),
                ('card_holder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Владелец карты')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название банка')),
                ('instructions', models.TextField(blank=True, help_text='Дополнительная информация для менеджеров', null=True, verbose_name='Инструкции для пополнения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки оплаты',
                'verbose_name_plural': 'Настройки оплаты',
            },
        ),
        migrations.CreateModel(
            name='TopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_tjs', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма в TJS')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма в USD')),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Курс на момент создания заявки', max_digits=10, verbose_name='Курс обмена (TJS/USD)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('transaction_proof', models.TextField(blank=True, help_text='Номер транзакции, скриншот и т.д.', null=True, verbose_name='Подтверждение перевода')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_topups', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Заявка на пополнение',
                'verbose_name_plural': 'Заявки на пополнение',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='clients_top_created_92313f_idx'), models.Index(fields=['status', 'created_at'], name='clients_top_status_e81500_idx')],
            },
        ),
    ]
