# Generated by Django 6.0.1 on 2026-01-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_paymentsettings_topuprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок объявления', max_length=200, verbose_name='Название')),
                ('content', models.TextField(help_text='Текст объявления', verbose_name='Содержание')),
                ('icon', models.CharField(default='📢', help_text='Используйте эмодзи или текст', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли это объявление на сайте', verbose_name='Активно')),
                ('order', models.IntegerField(default=0, help_text='Меньшее число = раньше в списке', verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
