# Generated by Django 6.0.1 on 2026-01-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка'), ('pending', 'Ожидание')], default='pending', max_length=20, verbose_name='Статус')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ API')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'SMS лог',
                'verbose_name_plural': 'SMS логи',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['client', 'sent_at'], name='clients_sms_client__08dcc1_idx'), models.Index(fields=['status'], name='clients_sms_status_42875a_idx')],
            },
        ),
    ]
