# Generated by Django 6.0.1 on 2026-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Системные логи',
                'verbose_name_plural': 'Системные логи',
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
    ]
