# Generated by Django 4.0.8 on 2026-01-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages_html', models.TextField(blank=True, null=True, verbose_name='HTML со списком пакетов')),
                ('packages_data', models.JSONField(blank=True, default=dict, verbose_name='Данные о пакетах')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Дата получения')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='package_info', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Информация о пакетах',
                'verbose_name_plural': 'Информация о пакетах',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
