# Generated by Django 4.0.8 on 2026-01-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_iptvinfo_stats_fields'),
        ('clients', '0022_clientpackageinfo'),
    ]

    operations = [
    ]
