# Generated by Django 4.0.8 on 2026-01-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_merge_20260123_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Автоматически рассчитывается по количеству клиентов', max_digits=5, verbose_name='Индивидуальная скидка %'),
        ),
    ]
