# Generated by Django 4.0.8 on 2026-01-27 09:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_profile_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manual_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Дополнительная скидка, выданная вручную администратором. Суммируется с автоматической.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ручная скидка % (бонус)'),
        ),
    ]
