# Generated by Django 4.0.8 on 2026-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_profile_manual_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dealer_sync_message',
            field=models.TextField(blank=True, help_text='Детали синхронизации или ошибки', null=True, verbose_name='Сообщение синхронизации'),
        ),
        migrations.AddField(
            model_name='client',
            name='dealer_sync_status',
            field=models.CharField(choices=[('pending', 'Ожидает синхронизации'), ('in_progress', 'Синхронизация...'), ('success', 'Синхронизирован'), ('failed', 'Ошибка синхронизации')], default='pending', help_text='Статус синхронизации клиента с сайтом дилера', max_length=20, verbose_name='Статус синхронизации с дилером'),
        ),
        migrations.AddField(
            model_name='client',
            name='dealer_synced_at',
            field=models.DateTimeField(blank=True, help_text='Когда произошла последняя синхронизация', null=True, verbose_name='Время синхронизации'),
        ),
    ]
